services:
  - type: worker
    name: izlabot
    env: python
    buildCommand: "pip install -r requirements.txt"
    runtime: docker
    startCommand: "python test_izlabot.py"

  - type: worker
    name: yuklabot
    env: python
    buildCommand: "pip install -r requirements.txt"
    runtime: docker
    startCommand: "python test_yukla.py"

