services:
  - type: web
    name: kino-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 test_izlabot.py"

  - type: worker
    name: kino-bot-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 test_yukla.py"
